env:
  browser: true
  es6: true
  jest: true
extends:
  - standard
  - standard-react
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  comma-dangle: ["error", "only-multiline"]

